spring.application.name=MotoShare

spring.datasource.url=jdbc:postgresql://localhost:5432/Bike_
spring.datasource.username=postgres
spring.datasource.password=2006

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

jwt.secret=motoshare-secret-key-motoshare-123456
jwt.expiration=86400000

# Email (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sourabh20092004@gmail.com
spring.mail.password=ledr qvhq xgyb byed
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
